CREATE TABLE IF NOT EXISTS product(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    value bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS tax(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS sale(
    product_id integer references product(id),
    tax_id integer references tax(id)
);

CREATE TABLE IF NOT EXISTS range_tax(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    taxid integer references tax(id),
    start bigint NOT NULL,
    final bigint NOT NULL,
    value integer NOT NULL
);

-- Datos para los productos

INSERT INTO product (name, value)
    values ('Cerveza', 3000);

INSERT INTO product (name, value)
    values ('Gaseosa', 2000);

INSERT INTO product (name, value)
    values ('Vino', 8000);

-- Datos para los impuestos
-- Donde un producto puede tener muchos impuestos

INSERT INTO tax (name)
    VALUES ('IVA');

INSERT INTO tax (name)
    VALUES ('Tasa bomberil');


--Relacion de datos entre product y tax

INSERT INTO sale (product_id, tax_id)
    VALUES  (1 , 1),
            (1 , 2),
            (2 , 1),
            (3 , 2);


-- Datos para rangos de impuestos
-- Donde un impuesto puede tener muchos rangos

INSERT INTO range_tax (taxid, start, final, value)
    VALUES  (2, 520, 4000, 20);