CREATE TABLE IF NOT EXISTS product(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    value bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS tax(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id integer references product(id),
    name text NOT NULL CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS range_tax(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tax_id integer references tax(id),
    start bigint NOT NULL,
    final bigint NOT NULL,
    value integer NOT NULL
);

-- Datos para los productos

INSERT INTO product (name, value)
    values ('Cerveza', 3000);

INSERT INTO product (name, value)
    values ('Gaseosa', 2000);

INSERT INTO product (name, value)
    values ('Vino', 8000);

-- Datos para los impuestos
-- Donde un producto puede tener muchos impuestos

INSERT INTO tax (product_id, name)
    VALUES (1, 'IVA');

INSERT INTO tax (product_id, name)
    VALUES (1, 'Tasa bomberil');

INSERT INTO tax (product_id, name)
    VALUES (2, 'IVA');

INSERT INTO tax (product_id, name)
    VALUES (3, 'Tasa bomberil');

-- Datos para rangos de impuestos
-- Donde un impuesto puede tener muchos rangos

INSERT INTO range_tax (tax_id, start, final, value)
    VALUES  (1, 0, 4000, 20),
            (2, 0, 3500, 50),
            (3, 0, 4000, 0),
            (4, 3501, 10000, 2);